### ISSUE TITLE
redirect if no current user is available when mounting live view

### ISSUE THREAD

**Issue by grrrisu** [grrrisu/thundermoon-umbrella#45]
```
[error] GenServer #PID<0.567.0> terminating
** (Ecto.NoResultsError) expected at least one result but got none in query:

from u0 in Thundermoon.Accounts.User,
  where: u0.id == ^5

    (ecto) lib/ecto/repo/queryable.ex:77: Ecto.Repo.Queryable.one!/3
    (thundermoon_web) lib/thundermoon_web/live/counter_live.ex:14: ThundermoonWeb.CounterLive.mount/2
    (phoenix_live_view) lib/phoenix_live_view/view.ex:485: Phoenix.LiveView.View.call_mount/3
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:460: Phoenix.LiveView.Channel.verified_mount/9
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:mount, Phoenix.LiveView.Channel}
```

**Comment by grrrisu** [comment]
redirect is not possible on mount. 
This is not real problem but only in dev mode when changing the db between dev and integration.
